import Head from "next/head";
import Script from "next/script";
import React, { useEffect, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faBell,
    faChevronCircleDown,
    faCog,
    faCommentAlt,
    faExclamationCircle,
    faHome,
    faTachometerAlt,
    faUserPlus,
} from "@fortawesome/free-solid-svg-icons";
import classNames from "classnames";
import { useRouter } from "next/router";
import Simplebar from "simplebar-react";

const titleCase = require("voca/title_case");
const replace = require("voca/replace");
const split = require("voca/split");

function Admin(props) {
    const [collapsed, setCollapsed] = useState(false);
    const [urlPath, setUrlPath] = useState("");
    const [breadcrumb, setBreadcrumb] = useState([]);

    const { asPath } = useRouter();
    const router = useRouter();

    useEffect(() => {
        const path = split(asPath, "/");
        path.shift();

        setUrlPath(path[1]);

        const newBreadcrumb = path.map((row, i) => {
            const name = titleCase(replace(row, "_", " "));
            let current;

            if (i === path.length - 1) {
                current = true;
            } else {
                current = false;
            }

            return {
                name: name,
                current: current,
            };
        });

        setBreadcrumb(newBreadcrumb);
    }, []);

    const handleSidebarToggle = () => {
        setCollapsed(!collapsed);
    };
    const handleLogoutClick = () => {
        router.push("/login");
    };

    return (
        <React.Fragment>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Script src="/js/adminkit.js" />
            <div className="wrapper">
                <nav
                    id="sidebar"
                    className={classNames(
                        {
                            collapsed: collapsed,
                        },
                        "sidebar js-sidebar"
                    )}
                >
                    <Simplebar className="sidebar-content js-simplebar">
                        <a className="sidebar-brand" href="index.html">
                            <span className="align-middle">AdminKit</span>
                        </a>

                        <ul className="sidebar-nav">
                            <li
                                className={classNames(
                                    {
                                        active: urlPath === "dashboard",
                                    },
                                    "sidebar-item"
                                )}
                            >
                                <a className="sidebar-link" href="index.html">
                                    <FontAwesomeIcon
                                        className="icons"
                                        icon={faTachometerAlt}
                                    />{" "}
                                    <span className="align-middle">
                                        Dashboard
                                    </span>
                                </a>
                            </li>
                            <li className="sidebar-item">
                                <a
                                    data-bs-target="#dashboards"
                                    data-bs-toggle="collapse"
                                    className="sidebar-link collapsed"
                                    aria-expanded="false"
                                >
                                    <FontAwesomeIcon
                                        className="icons"
                                        icon={faChevronCircleDown}
                                    />
                                    <span className="align-middle">
                                        Dropdown
                                    </span>
                                </a>
                                <ul
                                    id="dashboards"
                                    className="sidebar-dropdown list-unstyled collapse"
                                    data-bs-parent="#sidebar"
                                >
                                    <li className="sidebar-item">
                                        <a
                                            className="sidebar-link"
                                            href="index.html"
                                        >
                                            Analytics
                                        </a>
                                    </li>
                                    <li className="sidebar-item">
                                        <a
                                            className="sidebar-link"
                                            href="dashboard-ecommerce.html"
                                        >
                                            E-Commerce{" "}
                                            <span className="sidebar-badge badge bg-primary">
                                                Pro
                                            </span>
                                        </a>
                                    </li>
                                    <li className="sidebar-item">
                                        <a
                                            className="sidebar-link"
                                            href="dashboard-crypto.html"
                                        >
                                            Crypto{" "}
                                            <span className="sidebar-badge badge bg-primary">
                                                Pro
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </Simplebar>
                </nav>

                <div className="main">
                    <nav className="navbar navbar-expand navbar-light navbar-bg">
                        <a
                            className="sidebar-toggle js-sidebar-toggle"
                            onClick={handleSidebarToggle}
                        >
                            <i className="hamburger align-self-center"></i>
                        </a>

                        <div className="navbar-collapse collapse">
                            <ul className="navbar-nav navbar-align">
                                <li className="nav-item dropdown">
                                    <a
                                        className="nav-icon dropdown-toggle"
                                        href="#"
                                        id="alertsDropdown"
                                        data-bs-toggle="dropdown"
                                    >
                                        <div className="position-relative">
                                            <FontAwesomeIcon
                                                className="icons"
                                                icon={faBell}
                                            />
                                            <span className="indicator">4</span>
                                        </div>
                                    </a>
                                    <div
                                        className="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0"
                                        aria-labelledby="alertsDropdown"
                                    >
                                        <div className="dropdown-menu-header">
                                            4 New Notifications
                                        </div>
                                        <div className="list-group">
                                            <a
                                                href="#"
                                                className="list-group-item"
                                            >
                                                <div className="row g-0 align-items-center">
                                                    <div className="col-2">
                                                        <FontAwesomeIcon
                                                            className="icons text-danger"
                                                            icon={
                                                                faExclamationCircle
                                                            }
                                                        />
                                                    </div>
                                                    <div className="col-10">
                                                        <div className="text-dark">
                                                            Update completed
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            Restart server 12 to
                                                            complete the update.
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            30m ago
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                            <a
                                                href="#"
                                                className="list-group-item"
                                            >
                                                <div className="row g-0 align-items-center">
                                                    <div className="col-2">
                                                        <FontAwesomeIcon
                                                            className="icons text-warning"
                                                            icon={faBell}
                                                        />
                                                    </div>
                                                    <div className="col-10">
                                                        <div className="text-dark">
                                                            Lorem ipsum
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            Aliquam ex eros,
                                                            imperdiet vulputate
                                                            hendrerit et.
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            2h ago
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                            <a
                                                href="#"
                                                className="list-group-item"
                                            >
                                                <div className="row g-0 align-items-center">
                                                    <div className="col-2">
                                                        <FontAwesomeIcon
                                                            icon="icons text-primary"
                                                            icon={faHome}
                                                        />
                                                    </div>
                                                    <div className="col-10">
                                                        <div className="text-dark">
                                                            Login from
                                                            192.186.1.8
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            5h ago
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                            <a
                                                href="#"
                                                className="list-group-item"
                                            >
                                                <div className="row g-0 align-items-center">
                                                    <div className="col-2">
                                                        <FontAwesomeIcon
                                                            className="icons text-success"
                                                            icon={faUserPlus}
                                                        />
                                                    </div>
                                                    <div className="col-10">
                                                        <div className="text-dark">
                                                            New connection
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            Christina accepted
                                                            your request.
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            14h ago
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div className="dropdown-menu-footer">
                                            <a href="#" className="text-muted">
                                                Show all notifications
                                            </a>
                                        </div>
                                    </div>
                                </li>
                                <li className="nav-item dropdown">
                                    <a
                                        className="nav-icon dropdown-toggle"
                                        href="#"
                                        id="messagesDropdown"
                                        data-bs-toggle="dropdown"
                                    >
                                        <div className="position-relative">
                                            <FontAwesomeIcon
                                                className="icons"
                                                icon={faCommentAlt}
                                            />
                                        </div>
                                    </a>
                                    <div
                                        className="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0"
                                        aria-labelledby="messagesDropdown"
                                    >
                                        <div className="dropdown-menu-header">
                                            <div className="position-relative">
                                                4 New Messages
                                            </div>
                                        </div>
                                        <div className="list-group">
                                            <a
                                                href="#"
                                                className="list-group-item"
                                            >
                                                <div className="row g-0 align-items-center">
                                                    <div className="col-2">
                                                        <img
                                                            src="img/avatars/avatar-5.jpg"
                                                            className="avatar img-fluid rounded-circle"
                                                            alt="Vanessa Tucker"
                                                        />
                                                    </div>
                                                    <div className="col-10 ps-2">
                                                        <div className="text-dark">
                                                            Vanessa Tucker
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            Nam pretium turpis
                                                            et arcu. Duis arcu
                                                            tortor.
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            15m ago
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                            <a
                                                href="#"
                                                className="list-group-item"
                                            >
                                                <div className="row g-0 align-items-center">
                                                    <div className="col-2">
                                                        <img
                                                            src="img/avatars/avatar-2.jpg"
                                                            className="avatar img-fluid rounded-circle"
                                                            alt="William Harris"
                                                        />
                                                    </div>
                                                    <div className="col-10 ps-2">
                                                        <div className="text-dark">
                                                            William Harris
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            Curabitur ligula
                                                            sapien euismod
                                                            vitae.
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            2h ago
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                            <a
                                                href="#"
                                                className="list-group-item"
                                            >
                                                <div className="row g-0 align-items-center">
                                                    <div className="col-2">
                                                        <img
                                                            src="img/avatars/avatar-4.jpg"
                                                            className="avatar img-fluid rounded-circle"
                                                            alt="Christina Mason"
                                                        />
                                                    </div>
                                                    <div className="col-10 ps-2">
                                                        <div className="text-dark">
                                                            Christina Mason
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            Pellentesque auctor
                                                            neque nec urna.
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            4h ago
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                            <a
                                                href="#"
                                                className="list-group-item"
                                            >
                                                <div className="row g-0 align-items-center">
                                                    <div className="col-2">
                                                        <img
                                                            src="img/avatars/avatar-3.jpg"
                                                            className="avatar img-fluid rounded-circle"
                                                            alt="Sharon Lessman"
                                                        />
                                                    </div>
                                                    <div className="col-10 ps-2">
                                                        <div className="text-dark">
                                                            Sharon Lessman
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            Aenean tellus metus,
                                                            bibendum sed,
                                                            posuere ac, mattis
                                                            non.
                                                        </div>
                                                        <div className="text-muted small mt-1">
                                                            5h ago
                                                        </div>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                        <div className="dropdown-menu-footer">
                                            <a href="#" className="text-muted">
                                                Show all messages
                                            </a>
                                        </div>
                                    </div>
                                </li>
                                <li className="nav-item dropdown">
                                    <a
                                        className="nav-icon dropdown-toggle d-inline-block d-sm-none"
                                        href="#"
                                        data-bs-toggle="dropdown"
                                    >
                                        <FontAwesomeIcon
                                            className="icons"
                                            icon={faCog}
                                        />
                                    </a>

                                    <a
                                        className="nav-link dropdown-toggle d-none d-sm-inline-block"
                                        href="#"
                                        data-bs-toggle="dropdown"
                                    >
                                        <img
                                            src="img/avatars/avatar.jpg"
                                            className="avatar img-fluid rounded me-1"
                                            alt="Charles Hall"
                                        />{" "}
                                        <span className="text-dark">
                                            Charles Hall
                                        </span>
                                    </a>
                                    <div className="dropdown-menu dropdown-menu-end">
                                        <a
                                            className="dropdown-item"
                                            href="pages-profile.html"
                                        >
                                            <i
                                                className="align-middle me-1"
                                                data-feather="user"
                                            ></i>{" "}
                                            Profile
                                        </a>
                                        <div className="dropdown-divider"></div>
                                        <a
                                            className="dropdown-item"
                                            href="#"
                                            onClick={handleLogoutClick}
                                        >
                                            Logout
                                        </a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </nav>

                    <main className="content">
                        <div className="container-fluid p-0">
                            <nav aria-label="breadcrumb">
                                <ol className="breadcrumb">
                                    {breadcrumb.map((row, i) => (
                                        <li
                                            className={classNames(
                                                {
                                                    active: row.current,
                                                },
                                                "breadcrumb-item"
                                            )}
                                            key={i}
                                        >
                                            {row.current ? (
                                                row.name
                                            ) : (
                                                <a href="#">{row.name}</a>
                                            )}
                                        </li>
                                    ))}
                                </ol>
                            </nav>
                            <h1 className="h3 mb-3">Analytics Dashboard</h1>
                            {props.children}
                        </div>
                    </main>

                    <footer className="footer">
                        <div className="container-fluid">
                            <div className="row text-muted">
                                <div className="col-6 text-start">
                                    <p className="mb-0">
                                        <a
                                            className="text-muted"
                                            href="https://adminkit.io/"
                                            target="_blank"
                                        >
                                            <strong>AdminKit</strong>
                                        </a>{" "}
                                        &copy;
                                    </p>
                                </div>
                                <div className="col-6 text-end">
                                    <ul className="list-inline">
                                        <li className="list-inline-item">
                                            <a
                                                className="text-muted"
                                                href="https://adminkit.io/"
                                                target="_blank"
                                            >
                                                Support
                                            </a>
                                        </li>
                                        <li className="list-inline-item">
                                            <a
                                                className="text-muted"
                                                href="https://adminkit.io/"
                                                target="_blank"
                                            >
                                                Help Center
                                            </a>
                                        </li>
                                        <li className="list-inline-item">
                                            <a
                                                className="text-muted"
                                                href="https://adminkit.io/"
                                                target="_blank"
                                            >
                                                Privacy
                                            </a>
                                        </li>
                                        <li className="list-inline-item">
                                            <a
                                                className="text-muted"
                                                href="https://adminkit.io/"
                                                target="_blank"
                                            >
                                                Terms
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
        </React.Fragment>
    );
}

export default Admin;
